live_config_reload = true
import = ["/home/orhun/.config/alacritty/theme.toml"]
# import = ["/home/orhun/.config/alacritty/gruvbox.toml"]

[window]
decorations = "full"
dynamic_title = true
opacity = 0.9

[shell]
program = "/bin/bash"

[env]
TERM = "xterm-256color"

[font]
size = 8.0

[font.bold]
family = "Ubuntu Mono Ligaturized"
style = "Bold"

[font.italic]
family = "Ubuntu Mono Ligaturized"
style = "Italic"

[font.normal]
family = "Ubuntu Mono Ligaturized"
style = "Regular"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Up"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Down"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "Vi"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Alt"
