# ----------------------------
# Indexed colors (16â€“17)
# ----------------------------
[[colors.indexed_colors]]
index = 16
color = "#D08770" # orange

[[colors.indexed_colors]]
index = 17
color = "#BF616A" # red


# ----------------------------
# Normal colors
# ----------------------------
[colors.normal]
black   = "#191D24"
red     = "#BF616A"
green   = "#A3BE8C"
yellow  = "#EBCB8B"
blue    = "#5E81AC"
magenta = "#B48EAD"
cyan    = "#8FBCBB"
white   = "#D8DEE9"


# ----------------------------
# Bright colors
# ----------------------------
[colors.bright]
black   = "#434C5E"
red     = "#C5727A"
green   = "#B1C89D"
yellow  = "#EFD49F"
blue    = "#81A1C1"
magenta = "#BE9DB8"
cyan    = "#9FC6C5"
white   = "#ECEFF4"


# ----------------------------
# Primary colors
# ----------------------------
[colors.primary]
background = "#191D24"
foreground = "#D8DEE9"


# ----------------------------
# Selection colors
# ----------------------------
[colors.selection]
background = "#3B4252"
foreground = "#ECEFF4"
